language: python
python: "3.9"
services:
  - docker

script:
  - export PYTHONPATH=$(pwd)
  - pip install -r requirements.txt
  - chmod 777 run_tests.sh && ./run_tests.sh

deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: "gb_world_weather_forecast"
  env: "Gbworldweatherforecast-env"

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY

  bucket_name: weather-forecast-app-bucket

  bucket_path: "docker"
  on:
    branch: master